Different improvements

diff --git a/.scripts/gatekeeper b/.scripts/gatekeeper
--- a/.scripts/gatekeeper
+++ b/.scripts/gatekeeper
@@ -1,51 +1,43 @@
 #!/bin/zsh
 
 gatekeeper () (
-  GRN="\e[32m"
-  RED="\e[31m"
-  NC="\033[0m"
-
   case $1 in
     (disable)
-      if [ $2 = --global ] && [ "${*:3}" = "" ]; then
-        sudo spctl --master-disable
+      if [ -z $2 ]; then
+        sudo spctl --master-disable >/dev/null 2>&1
+        if [ $? -eq 0 ]; then
+          echo "🔓 GateKeeper disabled globally"
+        else
+          echo -r "An error occured, please try again"
+        fi
       else
         for app in "${@:2}"; do
+          app_name=$(printf "%s\n" "${app##*/}")
           sudo xattr -r -d com.apple.quarantine $app 2> /dev/null
           if [ $? -eq 0 ]; then
-            app_name=$(printf "%s\n" "${app##*/}")
-            echo "${GRN}🔓 GateKeeper disabled for $app_name$NC"
+            echo "🔓 GateKeeper disabled for $app_name"
           else
-            echo "${RED}❌ Can't disable GateKeeper for $app$NC"
+            echo -r "Can't disable GateKeeper for $app_name"
           fi
         done
-      fi
-      ;;
-
-    (global)
-      sudo spctl --master-disable >/dev/null 2>&1
-      if [ $? -eq 0 ]; then
-        echo "${GRN}🔓 GateKeeper disabled globally$NC"
-      else
-        echo "${RED}There was a problem disabling GateKeeper, please try again$NC"
       fi
       ;;
 
     (enable)
       sudo spctl --master-enable >/dev/null 2>&1
       if [ $? -eq 0 ]; then
-        echo "${GRN}🔒 GateKeeper enabled globally$NC"
+        echo "🔒 GateKeeper enabled globally"
       else
-        echo "${RED}There was a problem enabling GateKeeper, please try again$NC"
+        echo -r "There was a problem enabling GateKeeper, please try again"
       fi
       ;;
 
     (*)
-      echo "Usage: gatekeeper <command>\n"
+      echo "Usage: gatekeeper <command>"
+      echo
       echo "Commands:"
-      echo "  disable\t  Disable checks for one or multiple applications"
-      echo "  global\t  Disable checks globally"
-      echo "  enable\t  Enable checks globally"
+      echo "  disable [apps] \t Disable checks for one or multiple app, or globally if no apps are provided"
+      echo "  enable \t\t Enable checks globally"
       ;;
   esac
 )
